# Generated by Django 5.0.1 on 2024-02-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quickmart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='catagory',
        ),
    ]
